name: Periodic Ping

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - run: curl -I "https://pokeapi.co/api/v2/pokemon/"